- name: configuring catalouge application
  hosts: localhost
  tasks:
    - name: disabling default module 
      ansible.builtin.command: dnf module disable nodejs -y
        
    - name: enableing nodejs module 
      ansible.builtin.command: dnf module enable nodejs:20 -y
    
    - name: installing nodejs 
      ansible.builtin.package:
        name: nodejs
        state: latest 
#useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
    - name: adding user 
      ansible.builtin.user:
        name: roboshop
        home: /app
        shell: /sbin/nologin
        comment: roboshop system user 
        state: present

    - name: directory creation
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: changing directory
      ansible.builtin.command: cd /app 

    - name: downloading and unziping files 
      ansible.builtin.command: curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    
    - name: unziping file 
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app 
    
    - name: run command 
      ansible.builtin.command: npm install

    - name: copy file 
      ansible.builtin.copy:
        src: Ansible/Robshop/catalouge.service
        dest: /etc/systemd/system/catalogue.service 

    - name: service start
      ansible.builtin.service:
        name: catalogue.service
        state: started
        enabled: yes 
    
    - name: command
      ansible.builtin.command: systemctl daemon-reload

    - name: copy mongo repo 
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: installing 
      ansible.builtin.package:
        - name: mongodb-mongosh
          state: present

#==========

# - name: Configure Catalogue
#   hosts: localhost
#   become: yes

#   vars:
#     mongodb_host: 172.31.0.10

#   tasks:

#     - name: Disable nodejs module
#       command: dnf module disable nodejs -y

#     - name: Enable nodejs 20 module
#       command: dnf module enable nodejs:20 -y

#     - name: Install packages
#       package:
#         name:
#           - nodejs
#           - unzip
#         state: present

#     - name: Create roboshop user
#       user:
#         name: roboshop
#         system: yes
#         home: /app
#         shell: /sbin/nologin

#     - name: Create app directory
#       file:
#         path: /app
#         state: directory

#     - name: Download artifact
#       get_url:
#         url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
#         dest: /tmp/catalogue.zip

#     - name: Extract artifact
#       unarchive:
#         src: /tmp/catalogue.zip
#         dest: /app
#         remote_src: yes

#     - name: Install npm dependencies
#       command: npm install
#       args:
#         chdir: /app

#     - name: Copy service file
#       copy:
#         src: catalogue.service
#         dest: /etc/systemd/system/catalogue.service

#     - name: Reload systemd
#       systemd:
#         daemon_reload: yes

#     - name: Start service
#       systemd:
#         name: catalogue
#         enabled: yes
#         state: started