- name: frontend 
  hosts: localhost
  become : yes
  tasks:
    - name: disable prvious nginix module 
      ansible.builtin.shell: |
        dnf module disable nginx -y
        dnf module enable nginx:1.24 -y
        dnf install nginx -y
        systemctl enable nginx
        systemctl restart nginx 
        rm -rf /usr/share/nginx/html/* 
        curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        cd /usr/share/nginx/html 
        unzip /tmp/frontend.zip
    
    - name: copy file 
      ansible.builtin.copy:
        src: /Users/yallareddy/Desktop/softwares/Myscripts/Ansible/Roboshop/nginx.conf
        dest: /etc/nginx/nginx.conf
        
    - name: restart the service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes